const $=s=>document.querySelector(s);let dataset=null,analysis=null;
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2800)}
async function readFile(f){if(f.name.toLowerCase().endsWith('.csv'))return await f.text();return btoa(String.fromCharCode(...new Uint8Array(await f.arrayBuffer())))}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function canvas(c){let d=devicePixelRatio,w=c.offsetWidth,h=c.offsetHeight;c.width=w*d;c.height=h*d;let x=c.getContext('2d');x.scale(d,d);x.font='10px Manrope';return[x,w,h]}
function bar(c,l,v){let[x,w,h]=canvas(c),p={l:34,r:8,t:12,b:38},max=Math.max(...v,1),a=w-p.l-p.r,bw=Math.max(8,a/v.length*.55);x.strokeStyle='#e9eeea';for(let i=0;i<4;i++){let y=p.t+(h-p.t-p.b)*i/3;x.beginPath();x.moveTo(p.l,y);x.lineTo(w-p.r,y);x.stroke()}v.forEach((n,i)=>{let X=p.l+a*(i+.5)/v.length,Y=p.t+(h-p.t-p.b)*(1-n/max);x.fillStyle=i===0?'#ff8a5b':'#185b43';x.fillRect(X-bw/2,Y,bw,h-p.b-Y);x.save();x.translate(X,h-14);x.rotate(-.4);x.textAlign='right';x.fillStyle='#738078';x.fillText(String(l[i]).slice(0,12),0,0);x.restore()})}
function render(out){analysis=out;$('#dashboard-title').textContent=$('#instruction').value.trim()||'Analysis result';$('#dashboard-subtitle').textContent='Validated deterministic analysis';$('#ai-summary p').textContent=out.answer;
$('#kpis').innerHTML=out.kpis.map(x=>'<article class="kpi"><div class="kpi-label">'+esc(x[0])+'</div><div class="kpi-value">'+esc(x[1])+'</div><div class="kpi-note">● '+esc(x[2])+'</div></article>').join('');
$('#insights').innerHTML=out.provenance.map(x=>'<article class="insight"><h3>Calculation provenance</h3><p>'+esc(x)+'</p></article>').join('');
if(out.chart){$('#charts').innerHTML='<article class="chart-card wide"><div class="card-title"><div><h3>'+esc(out.chart.title)+'</h3><small>Generated from the validated analysis result</small></div></div><canvas class="chart"></canvas></article>';bar($('.chart'),out.chart.labels,out.chart.values)}else $('#charts').innerHTML='<article class="chart-card wide"><h3>No chart required</h3><small>This question has a verified numerical answer.</small></article>';
let s=out.schema||[];$('#row-count').textContent=s.length+' columns profiled';$('#data-table').innerHTML='<thead><tr><th>Column</th><th>Type</th><th>Unique</th><th>Missing</th><th>Sample values</th></tr></thead><tbody>'+s.map(x=>'<tr><td>'+esc(x.name)+'</td><td>'+esc(x.kind)+'</td><td>'+x.unique+'</td><td>'+x.missing_pct+'%</td><td>'+esc(x.samples.join(', '))+'</td></tr>').join('')+'</tbody>';$('#onboarding').classList.add('hidden');$('#dashboard').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
async function generate(){if(!dataset)return;let q=$('#instruction').value.trim();if(!q)return toast('Please ask a specific data question.');try{$('#generate').disabled=true;$('#generate').textContent='Analyzing…';let content=await readFile(dataset.file),file=dataset.file.name.toLowerCase().endsWith('.csv')?btoa(unescape(encodeURIComponent(content))):content,res=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:dataset.file.name,file,question:q})}),out=await res.json();if(!res.ok)throw Error(out.error||'Analysis failed.');render(out)}catch(e){toast(e.message)}finally{$('#generate').disabled=false;$('#generate').innerHTML='Generate my dashboard <span>→</span>'}}
function useFile(f){if(!f)return;if(f.size>3*1024*1024)return toast('For reliable server analysis, choose a file smaller than 3 MB.');dataset={file:f};$('#file-name').textContent=f.name;$('#file-meta').textContent=(f.size/1024).toFixed(0)+' KB ready for analysis';$('#file-info').classList.remove('hidden');$('#dropzone').classList.add('hidden');$('#generate').disabled=false;toast('Data loaded — ask a specific question.')}
$('#file-input').addEventListener('change',e=>useFile(e.target.files[0]));['dragover','dragleave','drop'].forEach(t=>$('#dropzone').addEventListener(t,e=>{e.preventDefault();$('#dropzone').classList.toggle('drag',t==='dragover')}));$('#dropzone').addEventListener('drop',e=>useFile(e.dataTransfer.files[0]));document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{$('#instruction').value=b.dataset.prompt;$('#instruction').focus()});$('#generate').onclick=generate;$('#clear-file').onclick=()=>{dataset=null;$('#file-input').value='';$('#file-info').classList.add('hidden');$('#dropzone').classList.remove('hidden');$('#generate').disabled=true};$('#new-dashboard').onclick=()=>{$('#dashboard').classList.add('hidden');$('#onboarding').classList.remove('hidden')};$('#export').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(analysis,null,2)],{type:'application/json'}));a.download='dashly-analysis.json';a.click()};