const $ = s => document.querySelector(s);
let dataset = null;
const fileInput = $('#file-input'), generate = $('#generate'), instruction = $('#instruction');

function toast(text){ const el=$('#toast'); el.textContent=text; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2600); }
function parseCSV(text){ const rows=[]; let row=[], cell='', quote=false; for(let i=0;i<text.length;i++){const c=text[i], next=text[i+1]; if(c==='"'&&quote&&next==='"'){cell+='"';i++}else if(c==='"'){quote=!quote}else if(c===','&&!quote){row.push(cell.trim());cell=''}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&next==='\n')i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell=''}else cell+=c}row.push(cell.trim());if(row.some(Boolean))rows.push(row); const headers=rows.shift().map((h,i)=>h||`Column ${i+1}`);return rows.map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??'']))); }
async function readFile(file){ const name=file.name.toLowerCase(); if(name.endsWith('.csv')) return parseCSV(await file.text()); if(!window.XLSX) throw Error('Excel reader is still loading. Please try again in a moment.'); const wb=XLSX.read(await file.arrayBuffer(),{type:'array'}); return XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''}); }
function number(v){ if(typeof v==='number')return v; const x=Number(String(v).replace(/[$,%\s,]/g,''));return Number.isFinite(x)?x:null; }
function fields(rows){ const headers=Object.keys(rows[0]||{}); return {headers,numeric:headers.filter(h=>{let valid=0,total=0;rows.slice(0,300).forEach(r=>{if(String(r[h]).trim()){total++;if(number(r[h])!==null)valid++}});return total&&valid/total>.7}),categories:headers.filter(h=>{const vals=new Set(rows.slice(0,500).map(r=>String(r[h]).trim()).filter(Boolean));return vals.size>1&&vals.size<=30}),dates:headers.filter(h=>rows.slice(0,100).filter(r=>!isNaN(Date.parse(r[h]))&&String(r[h]).length>5).length>10)}; }
function fmt(v){ if(!Number.isFinite(v))return '—'; return Math.abs(v)>=1000000?(v/1e6).toFixed(1)+'M':Math.abs(v)>=1000?(v/1000).toFixed(1)+'k':new Intl.NumberFormat('en-US',{maximumFractionDigits:1}).format(v); }
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function drawBar(canvas, labels, values){ const ctx=canvas.getContext('2d'), w=canvas.width=canvas.offsetWidth*devicePixelRatio,h=canvas.height=canvas.offsetHeight*devicePixelRatio,d=devicePixelRatio;ctx.scale(d,d);const W=canvas.offsetWidth,H=canvas.offsetHeight,p={l:34,r:8,t:10,b:35},max=Math.max(...values,1);ctx.font='10px Manrope';ctx.fillStyle='#849087';ctx.strokeStyle='#e9eeea';for(let i=0;i<4;i++){let y=p.t+(H-p.t-p.b)*i/3;ctx.beginPath();ctx.moveTo(p.l,y);ctx.lineTo(W-p.r,y);ctx.stroke();ctx.fillText(fmt(max*(1-i/3)),0,y+3)}let avail=W-p.l-p.r,bw=Math.max(7,avail/values.length*.58);values.forEach((v,i)=>{let x=p.l+avail*(i+.5)/values.length,y=p.t+(H-p.t-p.b)*(1-v/max);ctx.fillStyle=i===values.length-1?'#ff8a5b':'#185b43';ctx.beginPath();ctx.roundRect(x-bw/2,y,bw,H-p.b-y,3);ctx.fill();ctx.save();ctx.translate(x,H-15);ctx.rotate(-.35);ctx.textAlign='right';ctx.fillStyle='#738078';ctx.fillText(String(labels[i]).slice(0,11),0,0);ctx.restore()}); }
function drawLine(canvas, labels, values){ const ctx=canvas.getContext('2d'),w=canvas.width=canvas.offsetWidth*devicePixelRatio,h=canvas.height=canvas.offsetHeight*devicePixelRatio,d=devicePixelRatio;ctx.scale(d,d);const W=canvas.offsetWidth,H=canvas.offsetHeight,p={l:6,r:8,t:14,b:25},min=Math.min(...values),max=Math.max(...values),range=max-min||1;ctx.strokeStyle='#e9eeea';for(let i=0;i<3;i++){let y=p.t+(H-p.t-p.b)*i/2;ctx.beginPath();ctx.moveTo(p.l,y);ctx.lineTo(W-p.r,y);ctx.stroke()}const pt=(v,i)=>[p.l+(W-p.l-p.r)*i/Math.max(values.length-1,1),p.t+(H-p.t-p.b)*(1-(v-min)/range)];ctx.beginPath();values.forEach((v,i)=>{let [x,y]=pt(v,i);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle='#185b43';ctx.lineWidth=2.5;ctx.stroke();ctx.lineTo(W-p.r,H-p.b);ctx.lineTo(p.l,H-p.b);ctx.closePath();ctx.fillStyle='rgba(201,243,107,.28)';ctx.fill();ctx.fillStyle='#185b43';values.forEach((v,i)=>{let[x,y]=pt(v,i);ctx.beginPath();ctx.arc(x,y,3,0,7);ctx.fill()});ctx.fillStyle='#738078';ctx.font='10px Manrope';ctx.textAlign='center';labels.forEach((l,i)=>{if(i%Math.ceil(labels.length/6)===0){let[x]=pt(0,i);ctx.fillText(String(l).slice(0,9),x,H-7)}}); }
function card(title, sub, type){return `<article class="chart-card ${type==='line'?'wide':''}"><div class="card-title"><div><h3>${esc(title)}</h3><small>${esc(sub)}</small></div><small>Auto-generated</small></div><canvas class="chart" data-type="${type}"></canvas></article>`}
function showDashboard(){ const rows=dataset.rows, f=fields(rows), metric=f.numeric[0], metric2=f.numeric[1], category=f.categories.find(x=>x!==metric), date=f.dates[0]; const values=metric?rows.map(r=>number(r[metric])||0):[]; const sum=values.reduce((a,b)=>a+b,0), avg=sum/(values.length||1); const unique=category?new Set(rows.map(r=>r[category]).filter(Boolean)).size:0;
 $('#dashboard-title').textContent=instruction.value.trim()?instruction.value.trim().replace(/^./,c=>c.toUpperCase()).slice(0,72):'Your data, at a glance'; $('#dashboard-subtitle').textContent=`Based on ${rows.length.toLocaleString()} rows from ${dataset.name}`; $('#ai-summary p').textContent=metric?`I found ${f.numeric.length} measurable field${f.numeric.length!==1?'s':''} and ${f.categories.length} useful dimensions. ${metric} is the strongest candidate for tracking performance, so I’ve surfaced its total, average, and key breakdowns.`:`Your dataset is primarily descriptive, so this view focuses on records, categories, and distribution.`;
 const kpis=metric?[['Total '+metric,fmt(sum),'Across all records'],['Average '+metric,fmt(avg),'Per record'],[category?'Unique '+category:'Data points',fmt(unique||rows.length),category?'Groups in the data':'Rows analyzed'],[metric2?'Avg. '+metric2:'Completeness',''+(metric2?fmt(rows.reduce((a,r)=>a+(number(r[metric2])||0),0)/rows.length):Math.round(rows.filter(r=>Object.values(r).some(Boolean)).length/rows.length*100)+'%'),metric2?'Secondary metric':'Valid records']]:[['Total records',fmt(rows.length),'Rows analyzed'],['Fields',fmt(f.headers.length),'Columns detected'],['Categories',fmt(f.categories.length),'Useful dimensions'],['Completeness','100%','Ready to explore']];
 $('#kpis').innerHTML=kpis.map(([a,b,c])=>`<article class="kpi"><div class="kpi-label">${esc(a)}</div><div class="kpi-value">${esc(b)}</div><div class="kpi-note">● ${esc(c)}</div></article>`).join('');
 let charts=[], chartData=[]; if(metric&&category){const groups={};rows.forEach(r=>{let k=r[category]||'Unspecified';groups[k]=(groups[k]||0)+(number(r[metric])||0)});let sorted=Object.entries(groups).sort((a,b)=>b[1]-a[1]).slice(0,9);charts.push(card(`${metric} by ${category}`,`Top ${sorted.length} groups · total ${metric}`,'bar'));chartData.push(['bar',sorted.map(x=>x[0]),sorted.map(x=>x[1])]);} if(metric&&date){const groups={};rows.forEach(r=>{let k=new Date(r[date]).toLocaleDateString('en-US',{month:'short',year:'2-digit'});groups[k]=(groups[k]||0)+(number(r[metric])||0)});let a=Object.entries(groups).slice(0,12);charts.push(card(`${metric} over time`,`Trend by ${date}`,'line'));chartData.push(['line',a.map(x=>x[0]),a.map(x=>x[1])]);} if(metric&&!charts.length){let sampled=rows.slice(0,12);charts.push(card(`${metric} across records`,'A quick look at your numeric data','bar'));chartData.push(['bar',sampled.map((_,i)=>`Row ${i+1}`),sampled.map(r=>number(r[metric])||0)]);} if(charts.length<2&&metric2&&category){const groups={};rows.forEach(r=>{let k=r[category]||'Other';groups[k]=(groups[k]||0)+(number(r[metric2])||0)});let a=Object.entries(groups).sort((a,b)=>b[1]-a[1]).slice(0,8);charts.push(card(`${metric2} by ${category}`,'Secondary metric breakdown','bar'));chartData.push(['bar',a.map(x=>x[0]),a.map(x=>x[1])]);}
 $('#charts').innerHTML=charts.join('')||`<article class="chart-card wide"><div class="card-title"><div><h3>Dataset structure</h3><small>Add a numeric field to unlock more charts.</small></div></div></article>`; [...document.querySelectorAll('.chart')].forEach((c,i)=>{let d=chartData[i]; if(d) d[0]==='line'?drawLine(c,d[1],d[2]):drawBar(c,d[1],d[2])});
 $('#row-count').textContent=`${rows.length.toLocaleString()} rows · ${f.headers.length} columns`; $('#data-table').innerHTML=`<thead><tr>${f.headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.slice(0,6).map(r=>`<tr>${f.headers.map(h=>`<td>${esc(r[h])}</td>`).join('')}</tr>`).join('')}</tbody>`;
 $('#onboarding').classList.add('hidden');$('#dashboard').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'});
}
async function useFile(file){if(!file)return;try{if(file.size>20*1024*1024)throw Error('Please choose a file smaller than 20MB.'); const rows=await readFile(file);if(!rows.length)throw Error('No usable rows found in this file.');dataset={rows,name:file.name};$('#file-name').textContent=file.name;$('#file-meta').textContent=`${rows.length.toLocaleString()} rows detected`;$('#file-info').classList.remove('hidden');$('#dropzone').classList.add('hidden');generate.disabled=false;toast('Data loaded — ready to generate.')}catch(e){toast(e.message)}}
fileInput.addEventListener('change',e=>useFile(e.target.files[0]));['dragover','dragleave','drop'].forEach(t=>$('#dropzone').addEventListener(t,e=>{e.preventDefault();$('#dropzone').classList.toggle('drag',t==='dragover')}));$('#dropzone').addEventListener('drop',e=>useFile(e.dataTransfer.files[0]));document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{instruction.value=b.dataset.prompt;instruction.focus()});generate.onclick=showDashboard;$('#clear-file').onclick=()=>{dataset=null;fileInput.value='';$('#file-info').classList.add('hidden');$('#dropzone').classList.remove('hidden');generate.disabled=true};$('#new-dashboard').onclick=()=>{$('#dashboard').classList.add('hidden');$('#onboarding').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})};window.addEventListener('resize',()=>{if(!$('#dashboard').classList.contains('hidden'))showDashboard()});
