const $=s=>document.querySelector(s);let dataset=null;
const stopWords=new Set('show me the and or for with from that this what how over time trends trend fluctuations fluctuation compare comparison results data dashboard give important executive overview identify unusual readings values top bottom performers performance'.split(' '));
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2800)}
function parseCSV(t){let rows=[],row=[],cell='',q=false;for(let i=0;i<t.length;i++){let c=t[i],n=t[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++}else if(c==='"')q=!q;else if(c===','&&!q){row.push(cell.trim());cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell=''}else cell+=c}row.push(cell.trim());if(row.some(Boolean))rows.push(row);let h=(rows.shift()||[]).map((x,i)=>x||'Column '+(i+1));return rows.map(r=>Object.fromEntries(h.map((x,i)=>[x,r[i]??''])))}
async function readFile(f){if(f.name.toLowerCase().endsWith('.csv'))return parseCSV(await f.text());if(!window.XLSX)throw Error('Excel reader is still loading. Try again in a moment.');let w=XLSX.read(await f.arrayBuffer(),{type:'array'});return XLSX.utils.sheet_to_json(w.Sheets[w.SheetNames[0]],{defval:''})}
function num(v){if(typeof v==='number')return v;let n=Number(String(v).replace(/[$,%\s,]/g,''));return Number.isFinite(n)?n:null}
function dateValue(v){if(v instanceof Date&&!isNaN(v))return v;let s=String(v).trim();if(!s||num(s)!==null||!/[a-zA-Z\/-]/.test(s))return null;let d=new Date(s);return isNaN(d)?null:d}
function profile(rows){let headers=Object.keys(rows[0]||{}),sample=rows.slice(0,500),numeric=[],dates=[],categories=[];headers.forEach(h=>{let values=sample.map(r=>r[h]).filter(v=>String(v).trim()!==''),n=values.filter(v=>num(v)!==null).length,d=values.filter(v=>dateValue(v)).length,u=new Set(values.map(String)).size;if(values.length&&n/values.length>=.7)numeric.push(h);else if(values.length&&d/values.length>=.7)dates.push(h);else if(u>1&&u<=Math.min(40,values.length*.7))categories.push(h)});return{headers,numeric,dates,categories}}
function words(s){return String(s).toLowerCase().replace(/[^a-z0-9]+/g,' ').split(' ').filter(x=>x.length>1&&!stopWords.has(x))}
function score(field,prompt,extra=[]){let h=words(field),p=words(prompt),x=0;h.forEach(w=>{if(p.includes(w))x+=8;extra.forEach(k=>{if(w.includes(k))x+=2})});return x}
function choose(list,prompt,extra=[]){return [...list].sort((a,b)=>score(b,prompt,extra)-score(a,prompt,extra))[0]}
function fmt(n){if(!Number.isFinite(n))return'—';return Math.abs(n)>=1e6?(n/1e6).toFixed(1)+'M':Math.abs(n)>=1000?(n/1000).toFixed(1)+'k':new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(n)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function group(rows,key,metric){let g={};rows.forEach(r=>{let k=r[key]||'Unspecified',v=metric?num(r[metric]):1;g[k]=(g[k]||0)+(metric?(v??0):1)});return Object.entries(g)}
function card(title,sub,type,wide=false){return '<article class="chart-card '+(wide?'wide':'')+'"><div class="card-title"><div><h3>'+esc(title)+'</h3><small>'+esc(sub)+'</small></div><small>Data-driven</small></div><canvas class="chart" data-type="'+type+'"></canvas></article>'}
function canvas(c){let d=devicePixelRatio,w=c.offsetWidth,h=c.offsetHeight;c.width=w*d;c.height=h*d;let x=c.getContext('2d');x.scale(d,d);x.font='10px Manrope';return[x,w,h]}
function drawBar(c,labels,values){let[x,w,h]=canvas(c),p={l:35,r:8,t:12,b:40},max=Math.max(...values,1),a=w-p.l-p.r;x.strokeStyle='#e9eeea';x.fillStyle='#849087';for(let i=0;i<4;i++){let y=p.t+(h-p.t-p.b)*i/3;x.beginPath();x.moveTo(p.l,y);x.lineTo(w-p.r,y);x.stroke();x.fillText(fmt(max*(1-i/3)),0,y+3)}let bw=Math.max(7,a/values.length*.6);values.forEach((v,i)=>{let X=p.l+a*(i+.5)/values.length,Y=p.t+(h-p.t-p.b)*(1-v/max);x.fillStyle=i===0?'#ff8a5b':'#185b43';x.fillRect(X-bw/2,Y,bw,h-p.b-Y);x.save();x.translate(X,h-15);x.rotate(-.4);x.textAlign='right';x.fillStyle='#738078';x.fillText(String(labels[i]).slice(0,12),0,0);x.restore()})}
function drawLine(c,labels,values){let[x,w,h]=canvas(c),p={l:8,r:8,t:14,b:25},min=Math.min(...values),max=Math.max(...values),range=max-min||1,pt=(v,i)=>[p.l+(w-p.l-p.r)*i/Math.max(1,values.length-1),p.t+(h-p.t-p.b)*(1-(v-min)/range)];x.strokeStyle='#e9eeea';for(let i=0;i<3;i++){let y=p.t+(h-p.t-p.b)*i/2;x.beginPath();x.moveTo(p.l,y);x.lineTo(w-p.r,y);x.stroke()}x.beginPath();values.forEach((v,i)=>{let z=pt(v,i);i?x.lineTo(...z):x.moveTo(...z)});x.strokeStyle='#185b43';x.lineWidth=2.5;x.stroke();x.fillStyle='#185b43';values.forEach((v,i)=>{let z=pt(v,i);x.beginPath();x.arc(...z,3,0,7);x.fill()});x.fillStyle='#738078';x.textAlign='center';labels.forEach((l,i)=>{if(i%Math.ceil(labels.length/6)===0)x.fillText(String(l).slice(0,10),pt(0,i)[0],h-7)})}
function dashboard(){let rows=dataset.rows,p=profile(rows),prompt=$('#instruction').value.trim(),metric=choose(p.numeric,prompt,['revenue','sales','cost','price','temperature','pressure','health','score','amount','count']),second=p.numeric.find(x=>x!==metric),cat=choose(p.categories,prompt,['region','location','category','type','department','patient','status']),date=choose(p.dates,prompt,['date','time','month','day','year']),values=metric?rows.map(r=>num(r[metric])).filter(n=>n!==null):[],sum=values.reduce((a,b)=>a+b,0),avg=sum/(values.length||1),min=Math.min(...values),max=Math.max(...values);
let focus=metric||cat||date||'dataset';$('#dashboard-title').textContent=prompt?prompt.replace(/^./,c=>c.toUpperCase()).slice(0,82):'Overview of '+focus;$('#dashboard-subtitle').textContent=rows.length.toLocaleString()+' rows · '+p.headers.length+' columns · '+dataset.name;
$('#ai-summary p').textContent='Dashly matched your request to '+[metric,cat,date].filter(Boolean).join(', ') + '. The calculations and charts below are generated from those fields, not from a fixed template.';
let kpis=metric?[['Total '+metric,fmt(sum),'Across valid values'],['Average '+metric,fmt(avg),'Per record'],['Range',fmt(min)+' – '+fmt(max),'Lowest to highest'],[cat?'Groups in '+cat:'Valid values',fmt(cat?new Set(rows.map(r=>r[cat])).size:values.length),cat?'Categories detected':'Numeric observations']]:[['Total records',fmt(rows.length),'Rows analyzed'],['Columns',fmt(p.headers.length),'Fields detected'],['Numeric fields',fmt(p.numeric.length),'Measurable values'],['Categories',fmt(p.categories.length),'Useful dimensions']];
$('#kpis').innerHTML=kpis.map(x=>'<article class="kpi"><div class="kpi-label">'+esc(x[0])+'</div><div class="kpi-value">'+esc(x[1])+'</div><div class="kpi-note">● '+esc(x[2])+'</div></article>').join('');
let insights=[];if(metric){insights.push(['Focus field','Using '+metric+' because it best matches your request.']);if(values.length>2){let sd=Math.sqrt(values.reduce((s,v)=>s+(v-avg)**2,0)/values.length);let unusual=values.filter(v=>Math.abs(v-avg)>2*sd).length;insights.push(['Variation',unusual?unusual+' unusually high or low '+metric+' values need attention.':'Values stay within a typical range; no 2σ outliers found.'])}}if(cat){let top=group(rows,cat,metric).sort((a,b)=>b[1]-a[1])[0];insights.push(['Leading group',top[0]+' has the '+(metric?'highest total '+metric:'most records')+' ('+fmt(top[1])+').'])}$('#insights').innerHTML=insights.slice(0,3).map(x=>'<article class="insight"><h3>'+esc(x[0])+'</h3><p>'+esc(x[1])+'</p></article>').join('');
let html=[],plans=[];if(metric&&date){let g={};rows.forEach(r=>{let d=dateValue(r[date]),v=num(r[metric]);if(d&&v!==null){let k=d.toISOString().slice(0,10);g[k]=(g[k]||0)+v}});let a=Object.entries(g).sort((a,b)=>a[0].localeCompare(b[0])).slice(-24);if(a.length>1){html.push(card(metric+' over time','Trend grouped by '+date,'line',true));plans.push(['line',a.map(x=>x[0]),a.map(x=>x[1])])}}if(metric&&cat){let a=group(rows,cat,metric).sort((a,b)=>b[1]-a[1]).slice(0,10);html.push(card(metric+' by '+cat,'Top '+a.length+' groups','bar'));plans.push(['bar',a.map(x=>x[0]),a.map(x=>x[1])])}if(!html.length&&metric){let a=rows.slice(0,12).map((r,i)=>['Row '+(i+1),num(r[metric])??0]);html.push(card(metric+' across records','First 12 observations','bar',true));plans.push(['bar',a.map(x=>x[0]),a.map(x=>x[1])])}if(!html.length&&cat){let a=group(rows,cat).sort((a,b)=>b[1]-a[1]).slice(0,10);html.push(card('Records by '+cat,'Distribution of categories','bar',true));plans.push(['bar',a.map(x=>x[0]),a.map(x=>x[1])])}if(!html.length)html.push('<article class="chart-card wide"><h3>Dataset structure</h3><small>Add a numeric, date, or repeated category column to generate charts.</small></article>');
$('#charts').innerHTML=html.join('');[...document.querySelectorAll('.chart')].forEach((c,i)=>plans[i][0]==='line'?drawLine(c,plans[i][1],plans[i][2]):drawBar(c,plans[i][1],plans[i][2]));
$('#row-count').textContent=rows.length.toLocaleString()+' rows · '+p.headers.length+' columns';$('#data-table').innerHTML='<thead><tr>'+p.headers.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.slice(0,6).map(r=>'<tr>'+p.headers.map(h=>'<td>'+esc(r[h])+'</td>').join('')+'</tr>').join('')+'</tbody>';$('#onboarding').classList.add('hidden');$('#dashboard').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
async function useFile(f){if(!f)return;try{if(f.size>20*1024*1024)throw Error('Please choose a file smaller than 20MB.');let rows=await readFile(f);if(!rows.length)throw Error('No usable rows found.');dataset={rows,name:f.name};$('#file-name').textContent=f.name;$('#file-meta').textContent=rows.length.toLocaleString()+' rows detected';$('#file-info').classList.remove('hidden');$('#dropzone').classList.add('hidden');$('#generate').disabled=false;toast('Data loaded — ready to generate.')}catch(e){toast(e.message)}}
$('#file-input').addEventListener('change',e=>useFile(e.target.files[0]));['dragover','dragleave','drop'].forEach(t=>$('#dropzone').addEventListener(t,e=>{e.preventDefault();$('#dropzone').classList.toggle('drag',t==='dragover')}));$('#dropzone').addEventListener('drop',e=>useFile(e.dataTransfer.files[0]));document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{$('#instruction').value=b.dataset.prompt;$('#instruction').focus()});$('#generate').onclick=dashboard;$('#clear-file').onclick=()=>{dataset=null;$('#file-input').value='';$('#file-info').classList.add('hidden');$('#dropzone').classList.remove('hidden');$('#generate').disabled=true};$('#new-dashboard').onclick=()=>{$('#dashboard').classList.add('hidden');$('#onboarding').classList.remove('hidden')};$('#export').onclick=()=>{let h=Object.keys(dataset.rows[0]),csv=[h,...dataset.rows.map(r=>h.map(k=>JSON.stringify(r[k]??'')).join(','))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=dataset.name.replace(/\.[^.]+$/,'')+'-export.csv';a.click();URL.revokeObjectURL(a.href)};window.addEventListener('resize',()=>{if(!$('#dashboard').classList.contains('hidden'))dashboard()});